FROM golang:1.14 as serverbuilder
WORKDIR /servers
COPY servers .
WORKDIR /servers/processor
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main

FROM alpine:latest as certs
RUN apk --update add ca-certificates

FROM scratch

COPY --from=serverbuilder /servers/processor/main  /server/main
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

WORKDIR  /server

CMD ["./main"]
