version: '2'
services:
  mongodb:
      image: "mongo:3"
      ports:
        - "27017:27017"
  nats:
      image: "nats:1.1.0"
      ports:
        - 4222:4222/tcp
  server-client:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
         - DATABASE_URL=mongodb:27017
         - LOG_CONSOLE=true
         - LOG_LEVEL=Debug
         - LOG_USE_NATS=false
         - LOG_USE_NATS=false;
         - LOG_LEVEL=Debug;
         - MONGO_URL=localhost:32768;
         - STRAVA_CLIENT_ID=12880;
         - STRAVA_CLIENT_SECRET=c61800b62c34c0866c20a22bd4cddf6a1b40aa23;
         - STRAVA_REDIRECT_URI=http://localhost:8091/api/v1/login/validate
      ports:
          - "8091:8091"
  server-api:
    build:
        context: .
        dockerfile: Dockerfile-api
    environment:
      - DATABASE_URL=mongodb:27017
      - LOG_CONSOLE=true
      - LOG_LEVEL=Debug
      - LOG_USE_NATS=false
      - LOG_USE_NATS=false;
      - LOG_LEVEL=Debug;
      - MONGO_URL=localhost:32768;
      - STRAVA_CLIENT_ID=12880;
      - STRAVA_CLIENT_SECRET=c61800b62c34c0866c20a22bd4cddf6a1b40aa23;
      - STRAVA_REDIRECT_URI=http://localhost:8091/api/v1/login/validate
    ports:
      - "8092:8091"
  server-processor:
    build:
        context: .
        dockerfile: Dockerfile-processor
    environment:
      - DATABASE_URL=mongodb:27017
      - LOG_CONSOLE=true
      - LOG_LEVEL=Debug
      - LOG_USE_NATS=false
      - LOG_USE_NATS=false;
      - LOG_LEVEL=Debug;
      - MONGO_URL=localhost:32768;
      - STRAVA_CLIENT_ID=12880;
      - STRAVA_CLIENT_SECRET=c61800b62c34c0866c20a22bd4cddf6a1b40aa23;
      - STRAVA_REDIRECT_URI=http://localhost:8091/api/v1/login/validate